# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

strategy:
  matrix:
    py36_linux:
      imageName: "Ubuntu-16.04"
      python.version: '3.6'
      cibw_build: cp36-manylinux*
    py37_linux:
      imageName: "Ubuntu-16.04"
      python.version: '3.7'
      cibw_build: cp37-manylinux*
    py38_linux:
      imageName: "Ubuntu-16.04"
      python.version: '3.8'
      cibw_build: cp38-manylinux*
    py36_mac:
      imageName: "macos-10.13"
      python.version: '3.6'
      cibw_build: cp36-macosx*
    py37_mac:
      imageName: "macos-10.13"
      python.version: '3.7'
      cibw_build: cp37-macosx*
    py38_mac:
      imageName: "macos-10.13"
      python.version: '3.8'
      cibw_build: cp38-macosx*
    py36_windows:
      imageName: "windows-latest"
      python.version: '3.6'
      cibw_build: cp36-win*
    py37_windows:
      imageName: "windows-latest"
      python.version: '3.7'
      cibw_build: cp37-win*
    py38_windows:
      imageName: "windows-latest"
      python.version: '3.8'
      cibw_build: cp38-win*

pool:
  vmImage: $(imageName)

variables:
  CIBW_BUILD: $(cibw_build)
  CIBW_BEFORE_BUILD: python -m pip install -U cython numpy

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install -U pip
    python -m pip install -U cython numpy
    python -m pip install -U pytest pytest-azurepipelines
    python -m pip install -U wheel cibuildwheel
    python -m pip install -U twine
  displayName: 'Install dependencies'

- script: |
    cd lib
    git clone https://github.com/kimwalisch/primesieve.git
    cd primesieve
    git checkout v7.4
    cd ../..
  displayName: 'Git primesieve lib'

- script: |
    python setup.py install
  displayName: 'Install'

- script: |
    pytest
  displayName: 'pytest'

- script: |
    python -m cibuildwheel --print-build-identifiers
    python -m cibuildwheel --output-dir wheelhouse .
  displayName: 'Build'

- script: |
    python -m twine upload --skip-existing --verbose --repository-url https://test.pypi.org/legacy/ -u __token__ -p $(test_pypi) wheelhouse/*.whl
  displayName: 'Upload'
